/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PetShopMaoHuaji;

import java.sql.PreparedStatement;
import java.sql.ResultSet;

/**
 *
 * @author HP
 */
public class Cetak extends javax.swing.JFrame {

    /**
     * Creates new form Cetak
//     */
//    public void tampil(Mao[] m) {
//        Mao mao = new Mao();
//
//        for (int i = 0; i < m.length; i++) {
//            m[i].tampilData();
//        }
//
//    }
//
//    public void cetak2() {
//        Mao[] m = {
//            
//            new cat(),
//            new Cute(),
//        };
//        
//        
//        Cetak c = new Cetak();
//        c.tampil(m);
//        
//        
//    }

    public Cetak(String idbreed) {
        initComponents();
        this.setLocationRelativeTo(null);
        // ===============================================================
        try {
            String sql = "select * from cat where id_breed = ?";
            PreparedStatement p = koneksi_mariadb.koneksiDB().prepareStatement(sql);

            p.setString(1, idbreed);

            ResultSet rs = p.executeQuery();

            while (rs.next()) {
                breed.setText(rs.getString("breed"));
                colour.setText(rs.getString("colour"));
                gender.setText(rs.getString("gender"));
                price.setText(rs.getString("price"));
            }

        } catch (Exception e) {

            System.out.println(e);
        }
        // ===============================================================
        try {
            String sql = "select * from cute where ID_Breed = ?";
            PreparedStatement p = koneksi_mariadb.koneksiDB().prepareStatement(sql);

            p.setString(1, idbreed);

            ResultSet rs = p.executeQuery();

            while (rs.next()) {
                name.setText(rs.getString("Nama"));
                no.setText(rs.getString("Notelp"));
            }

        } catch (Exception e) {

            System.out.println(e);
        }
    }

    Cetak(Cute cute) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private Cetak() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        breed = new javax.swing.JLabel();
        colour = new javax.swing.JLabel();
        gender = new javax.swing.JLabel();
        no = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        price = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Breed");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, -1, -1));

        jLabel2.setText("Colour");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, -1, -1));

        jLabel3.setText("Gender");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        jLabel4.setText("Name Adopter");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, -1));

        jLabel5.setText("NoTelp");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, -1));

        jLabel6.setText("Price");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, -1, -1));

        breed.setText("jLabel7");
        getContentPane().add(breed, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, -1, -1));

        colour.setText("jLabel7");
        getContentPane().add(colour, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, -1, -1));

        gender.setText("jLabel7");
        getContentPane().add(gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, -1, -1));

        no.setText("jLabel7");
        getContentPane().add(no, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, -1, -1));

        name.setText("jLabel7");
        getContentPane().add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, -1, -1));

        price.setText("jLabel7");
        getContentPane().add(price, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PetShopMaoHuaji/h.jpg"))); // NOI18N
        jLabel9.setText("jLabel9");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 230, 110));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PetShopMaoHuaji/h.jpg"))); // NOI18N
        jLabel10.setText("jLabel9");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -80, 90, 120));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PetShopMaoHuaji/h.jpg"))); // NOI18N
        jLabel11.setText("jLabel9");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 90, 80));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PetShopMaoHuaji/h.jpg"))); // NOI18N
        jLabel12.setText("jLabel9");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 90, 80));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PetShopMaoHuaji/vjg.jpg"))); // NOI18N
        jLabel7.setText("jLabel7");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 320, 150));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PetShopMaoHuaji/vjg.jpg"))); // NOI18N
        jLabel8.setText("jLabel7");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 150));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cetak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cetak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cetak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cetak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cetak().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel breed;
    private javax.swing.JLabel colour;
    private javax.swing.JLabel gender;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel name;
    private javax.swing.JLabel no;
    private javax.swing.JLabel price;
    // End of variables declaration//GEN-END:variables
}
